# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/app_settings.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_AppSettings(object):
    def setupUi(self, AppSettings):
        AppSettings.setObjectName("AppSettings")
        AppSettings.resize(685, 475)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AppSettings.sizePolicy().hasHeightForWidth())
        AppSettings.setSizePolicy(sizePolicy)
        AppSettings.setMinimumSize(QtCore.QSize(685, 475))
        AppSettings.setMaximumSize(QtCore.QSize(685, 475))
        self.layoutWidget = QtWidgets.QWidget(AppSettings)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 601, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.apiSettings = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.apiSettings.setContentsMargins(0, 0, 0, 0)
        self.apiSettings.setObjectName("apiSettings")
        self.apiSettingsTitle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.apiSettingsTitle.setFont(font)
        self.apiSettingsTitle.setObjectName("apiSettingsTitle")
        self.apiSettings.addWidget(self.apiSettingsTitle)
        self.apiKey = QtWidgets.QHBoxLayout()
        self.apiKey.setObjectName("apiKey")
        self.apiKeyLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiKeyLabel.sizePolicy().hasHeightForWidth())
        self.apiKeyLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.apiKeyLabel.setFont(font)
        self.apiKeyLabel.setObjectName("apiKeyLabel")
        self.apiKey.addWidget(self.apiKeyLabel)
        self.apiKeyLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiKeyLineEdit.sizePolicy().hasHeightForWidth())
        self.apiKeyLineEdit.setSizePolicy(sizePolicy)
        self.apiKeyLineEdit.setObjectName("apiKeyLineEdit")
        self.apiKey.addWidget(self.apiKeyLineEdit)
        self.apiSettings.addLayout(self.apiKey)
        self.apiSecret = QtWidgets.QHBoxLayout()
        self.apiSecret.setObjectName("apiSecret")
        self.apiSecretLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiSecretLabel.sizePolicy().hasHeightForWidth())
        self.apiSecretLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.apiSecretLabel.setFont(font)
        self.apiSecretLabel.setObjectName("apiSecretLabel")
        self.apiSecret.addWidget(self.apiSecretLabel)
        self.apiSecretLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiSecretLineEdit.sizePolicy().hasHeightForWidth())
        self.apiSecretLineEdit.setSizePolicy(sizePolicy)
        self.apiSecretLineEdit.setObjectName("apiSecretLineEdit")
        self.apiSecret.addWidget(self.apiSecretLineEdit)
        self.apiSettings.addLayout(self.apiSecret)
        self.accessToken = QtWidgets.QHBoxLayout()
        self.accessToken.setObjectName("accessToken")
        self.accessTokenLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accessTokenLabel.sizePolicy().hasHeightForWidth())
        self.accessTokenLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accessTokenLabel.setFont(font)
        self.accessTokenLabel.setObjectName("accessTokenLabel")
        self.accessToken.addWidget(self.accessTokenLabel)
        self.accessTokenLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accessTokenLineEdit.sizePolicy().hasHeightForWidth())
        self.accessTokenLineEdit.setSizePolicy(sizePolicy)
        self.accessTokenLineEdit.setObjectName("accessTokenLineEdit")
        self.accessToken.addWidget(self.accessTokenLineEdit)
        self.apiSettings.addLayout(self.accessToken)
        self.accessTokenSecret = QtWidgets.QHBoxLayout()
        self.accessTokenSecret.setObjectName("accessTokenSecret")
        self.accessTokenSecretLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accessTokenSecretLabel.sizePolicy().hasHeightForWidth())
        self.accessTokenSecretLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accessTokenSecretLabel.setFont(font)
        self.accessTokenSecretLabel.setObjectName("accessTokenSecretLabel")
        self.accessTokenSecret.addWidget(self.accessTokenSecretLabel)
        self.accessTokenSecretLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accessTokenSecretLineEdit.sizePolicy().hasHeightForWidth())
        self.accessTokenSecretLineEdit.setSizePolicy(sizePolicy)
        self.accessTokenSecretLineEdit.setObjectName("accessTokenSecretLineEdit")
        self.accessTokenSecret.addWidget(self.accessTokenSecretLineEdit)
        self.apiSettings.addLayout(self.accessTokenSecret)
        self.layoutWidget1 = QtWidgets.QWidget(AppSettings)
        self.layoutWidget1.setGeometry(QtCore.QRect(480, 420, 158, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.dialogButtons = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.dialogButtons.setContentsMargins(0, 0, 0, 0)
        self.dialogButtons.setObjectName("dialogButtons")
        self.saveBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveBtn.setObjectName("saveBtn")
        self.dialogButtons.addWidget(self.saveBtn)
        self.closeBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.closeBtn.setObjectName("closeBtn")
        self.dialogButtons.addWidget(self.closeBtn)
        self.layoutWidget_4 = QtWidgets.QWidget(AppSettings)
        self.layoutWidget_4.setGeometry(QtCore.QRect(40, 220, 601, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.databaseSettings = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.databaseSettings.setContentsMargins(0, 0, 0, 0)
        self.databaseSettings.setObjectName("databaseSettings")
        self.databaseSettingsTitle = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.databaseSettingsTitle.setFont(font)
        self.databaseSettingsTitle.setObjectName("databaseSettingsTitle")
        self.databaseSettings.addWidget(self.databaseSettingsTitle)
        self.databaseName = QtWidgets.QHBoxLayout()
        self.databaseName.setObjectName("databaseName")
        self.databaseNameLabel = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseNameLabel.sizePolicy().hasHeightForWidth())
        self.databaseNameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.databaseNameLabel.setFont(font)
        self.databaseNameLabel.setObjectName("databaseNameLabel")
        self.databaseName.addWidget(self.databaseNameLabel)
        self.databaseNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseNameLineEdit.sizePolicy().hasHeightForWidth())
        self.databaseNameLineEdit.setSizePolicy(sizePolicy)
        self.databaseNameLineEdit.setObjectName("databaseNameLineEdit")
        self.databaseName.addWidget(self.databaseNameLineEdit)
        self.databaseSettings.addLayout(self.databaseName)
        self.databasePath = QtWidgets.QHBoxLayout()
        self.databasePath.setObjectName("databasePath")
        self.databasePathLabel = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databasePathLabel.sizePolicy().hasHeightForWidth())
        self.databasePathLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.databasePathLabel.setFont(font)
        self.databasePathLabel.setObjectName("databasePathLabel")
        self.databasePath.addWidget(self.databasePathLabel)
        self.databasePathLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databasePathLineEdit.sizePolicy().hasHeightForWidth())
        self.databasePathLineEdit.setSizePolicy(sizePolicy)
        self.databasePathLineEdit.setObjectName("databasePathLineEdit")
        self.databasePath.addWidget(self.databasePathLineEdit)
        self.databaseSettings.addLayout(self.databasePath)

        self.retranslateUi(AppSettings)
        QtCore.QMetaObject.connectSlotsByName(AppSettings)

    def retranslateUi(self, AppSettings):
        _translate = QtCore.QCoreApplication.translate
        AppSettings.setWindowTitle(_translate("AppSettings", "Dialog"))
        self.apiSettingsTitle.setText(_translate("AppSettings", "API Settings"))
        self.apiKeyLabel.setText(_translate("AppSettings", "API Key"))
        self.apiSecretLabel.setText(_translate("AppSettings", "API Secret"))
        self.accessTokenLabel.setText(_translate("AppSettings", "Access Token"))
        self.accessTokenSecretLabel.setText(_translate("AppSettings", "Access Token Secret"))
        self.saveBtn.setText(_translate("AppSettings", "Save"))
        self.closeBtn.setText(_translate("AppSettings", "Close"))
        self.databaseSettingsTitle.setText(_translate("AppSettings", "Database Settings"))
        self.databaseNameLabel.setText(_translate("AppSettings", "Database Name"))
        self.databasePathLabel.setText(_translate("AppSettings", "Database Path"))


